# Draw keymap diagrams using keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - 'config/*.keymap'
      - 'config/includes/*.dtsi'
      - keymap-drawer/config.yaml
      - .github/workflows/draw-keymaps.yml

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      keymap_patterns: 'config/*.keymap'
      config_path: keymap-drawer/config.yaml
      output_folder: keymap-drawer
      install_branch: main
      amend_commit: true
      draw_args: "sweep:'-k hypergolic'"
               # "sweep:'-k ferris/sweep'"
               # "sweep:'-k ferris/sweep --ghost-keys 20 31 32 37'"
               # "corneish_zen:'--ghost-keys 20 24 25 29 30 35'"
      json_path: keymap-drawer/layouts
